.github/workflows/test-windows.yml, CHANGES.md, README.md, setup.py
=> Autodetect GDAL_VERSION on Windows using gdalinfo

pyogrio/geopandas.py, pyogrio/tests/test_geopandas_io.py
=> ENH: support empty dataframes

README.md, docs/source/install.md, setup.py
=> DEP: require Python >= 3.8

MANIFEST.in, pyproject.toml, setup.py
Closes https://github.com/geopandas/pyogrio/issues/40
This is all a bit hard to understand how it exactly works .., but locally this seems to produce a good sdist with `python -m build --sdist`
=> Packaging - stop including cythonized C files in sdist

CHANGES.md, docs/source/errors.md, docs/source/index.md, docs/source/install.md, pyogrio/_err.pyx, pyogrio/_geometry.pyx, pyogrio/_io.pyx, pyogrio/errors.py, pyogrio/tests/test_geopandas_io.py, pyogrio/tests/test_raw_io.py
=> ENH: Better wrap GDAL errors and pass through GDAL exceptions 

.github/workflows/tests-conda.yml, ci/environment.yml
Closes https://github.com/geopandas/pyogrio/issues/36
=> CI: add conda based test suite (including Windows coverage)

pyogrio/geopandas.py
See https://github.com/geopandas/pyogrio/pull/5#discussion_r864642229
=> Don't import geopandas and pyproj inside GDALEnv

pyogrio/tests/test_path.py
=> Add missing "assert" calls in the "path" tests

README.md, docs/source/install.md
Also cleans up supported GDAL versions.
=> DOC: Update installation instructions to include PyPI

readthedocs.yml
When specifically doing updates on the docs, I noticed the building takes quite some time.
This should speed this up (but I cannot verify exact timings).
=> Speed up doc builds by using mambaforge

CHANGES.md, pyogrio/_io.pyx, pyogrio/geopandas.py, pyogrio/tests/test_geopandas_io.py
=> Support object columns containing non-string values (eg. float, datetime,...)

pyogrio/geopandas.py
From merging the CI linting PR without updating it to latest main ..
=> Fix up linting (flake8)

CHANGES.md, pyogrio/_io.pyx, pyogrio/tests/test_raw_io.py
Closes https://github.com/geopandas/pyogrio/issues/59
=> Allow writing missing (null)  geometries

pyogrio/_io.pyx
=> ENH: improve name of count of features to read from data source

docs/source/introduction.md
Resolves #193
This should only be merged after #189
=> DOC: Add examples of dataset & layer creation options

CHANGES.md, pyogrio/geopandas.py, pyogrio/tests/test_geopandas_io.py
Fix issue raised in #223: https://github.com/geopandas/pyogrio/pull/223#issuecomment-1474795893
=> Fix geometry type "2.5D Unknown" is not supported

docs/source/install.md, environment-dev.yml
This is the way I develop on windows...
=> DOC: instructions to setup development env on windows using conda

CHANGES.md, pyogrio/_io.pyx, pyogrio/raw.py, pyogrio/tests/test_raw_io.py
=> FIX: Raise error from GDALClose after write

CHANGES.md, pyogrio/geopandas.py, pyogrio/tests/test_arrow.py
Closes https://github.com/geopandas/pyogrio/issues/296
=> Add PYOGRIO_USE_ARROW environment variable to enable Arrow usage globally

pyogrio/_compat.py, pyogrio/geopandas.py
Closes https://github.com/geopandas/pyogrio/issues/344
=> COMPAT: remove usage of pd.to_datetime errors=ignore option

.circleci/config.yml
See https://discuss.circleci.com/t/linux-image-deprecations-and-eol-for-2024/50177
=> BLD: update circleci image for arm wheel building

ci/vcpkg.json
=> RLS/BLD: Ensure VCPKG brings in iconv library

CHANGES.md, setup.py
=> Remove direct usage of distutils from setup.py

docs/source/about.md, docs/source/index.md
I should have mentioned it explicitly in #481 so it could have happened in one PR, but the changes there had to be synced to the docs/index.md as well...
=> DOC: sync readme changes to docs

CHANGES.md, pyogrio/_io.pyx, pyogrio/tests/conftest.py, pyogrio/tests/test_core.py
=> BUG: fix decode error reading an sqlite file on windows
