CHANGES.md
README.md
benchmarks/test_core_benchmarks.py
pyogrio/__init__.py
pyogrio/_io.pyx
pyogrio/_ogr.pxd
pyogrio/core.py
pyogrio/tests/test_core.py

Resolves #12 
This is about 2-3x faster than reading full feature data (had hoped for faster), likely because the underlying geometry data still need to be read from disk in order to calculate the extent.
The main benefit of this is likely using these bounds to create a spatial index, and then selectively read features by FID (not yet implemented; later PR).
This also includes a bit of reorganization within the I/O related functions in Cython, to better re-use them between different top-level functions.

Add support for reading bounding boxes of features

---

CHANGES.md
pyogrio/_io.pyx
pyogrio/_ogr.pxd
pyogrio/geopandas.py
pyogrio/raw.py
pyogrio/tests/test_geopandas_io.py
pyogrio/tests/test_raw_io.py

This is experimenting with reading a subset based on an array of FIDs. Very much a draft (eg still needs tests, docs, etc), but good enough for running some benchmarks (will post them after a re-run).
The diff is not super clear: I splitted `get_features` to separate the processing of the geometry and fields (so this can be reused in `get_features_by_fid`). If you look at only the first commit, this is clearer. In the end, I am not sure if this was the best approach, as in theory it could also be combined in `get_features` and have a if/else switch at the moment to get the OGRFeature (switching between `OGR_L_GetNextFeature` and ``OGR_L_GetFeature``), since the rest of `get_features` and `get_features_by_fid` have a lot of overlap.

ENH: read features based on array of FIDs

---

README.md
docs/source/about.md
docs/source/concepts.md
docs/source/index.md
docs/source/install.md
docs/source/introduction.md
docs/source/known_issues.md
docs/source/supported_formats.md

This moves most of the content out of the README file into a series of documentation files, and clarifies some of the content.
Built docs [here](https://pyogrio--28.org.readthedocs.build/en/28/)
(ignore CI build failures, those are unrelated)

Restructure README into docs

---

.gitignore
pyogrio/geopandas.py

GDAL natively supports [more](https://gdal.org/user/virtual_file_systems.html) vsi schemes than `vsizip`. If we don't necessarily check for that one, you can already use storages like S3 out of the box.
```py
pyogrio.read_dataframe("/vsis3/{bucket}/{filename}")
pyogrio.write_dataframe(df, "/vsis3/{bucket}/{filename}", driver="GeoJSON")
```
I think that it would also be nice to support the `s3://{bucket}/{filename}` format as well, as we do in GeoPandas (Fiona) (ref #21). 
I just don't know how to test this. I tried the `moto` way of mocking S3 but it seems that GDAL somehow ignores that. I'd rather avoid setting up a bucket as[ Fiona did](https://github.com/Toblerity/Fiona/blob/885dbd11c5dcb2c61862faefc28bfbbff99954de/tests/test_vfs.py#L182-L187).

ENH: pass through vsi schemas like S3

---

docs/source/introduction.md
pyogrio/_io.pyx
pyogrio/core.py
pyogrio/tests/test_core.py

Resolves #23
This adds an array of numpy dtype names to the output of `read_info`.  This intentionally does not refactor the `fields` entry, because that is also used as input when writing files and easiest to use as a simple list-like.

ENH: Add dtypes to read_info

---

pyogrio/_io.pyx

Small clean-up to avoid those deprecation warnings

CLN: use object instead of np.object (numpy deprecation)

---

pyogrio/_io.pyx
pyogrio/tests/test_geopandas_io.py

Encountered this while adding `layer` support in dask-geopandas

BUG: properly raise error if layer could not be opened

---

CHANGES.md
benchmarks/test_raw_io_benchmarks.py
pyogrio/_io.pyx
pyogrio/geopandas.py
pyogrio/raw.py
pyogrio/tests/test_geopandas_io.py
pyogrio/tests/test_raw_io.py

Resolves #14
This expands the Cython layer to read in FID while reading features, unless `fids` are provided as input, in which case those are copied and returned.
Questions:
* do we want to make this the default behavior or opt-in?
* if opt-in, do we want this to be based solely on a keyword parameter to enable it, or do we also want to opt-in when `fids` are passed in?

ENH: Use FID to set GeoDataFrame index

---

.github/workflows/release_to_pypi.yml

This workflow creates both github release and PyPI release everytime we create a new tag starting `v` (as `v0.4.0`. 
To make PyPI work, I need @brendan-ward or @jorisvandenbossche to add a repository secret called `PYPI_API_TOKEN` containing PyPI access token (or access to PyPI so I can do it myself).
Edit: token added

GHA: add release action

---

docs/source/introduction.md
pyogrio/core.py
pyogrio/geopandas.py
pyogrio/raw.py
pyogrio/tests/conftest.py
pyogrio/tests/test_core.py
pyogrio/tests/test_geopandas_io.py
pyogrio/tests/test_path.py
pyogrio/tests/test_raw_io.py
pyogrio/util.py
setup.cfg

Closes #21
(certainly still need to add docs)

ENH: support URI schemes (zip://, s3://) by converting to vsi paths

---

pyogrio/tests/test_geopandas_io.py

This uses a custom (completely made up) CRS centered over Belgium to verify that a custom CRS can be round-tripped.
This should also ensure that GDAL data files / PROJ data files are used when reading / writing the file.

Add test for custom CRS read / write

---

docs/source/install.md
setup.py

Related to https://github.com/geopandas/pyogrio/issues/8
Currently, for installing on source on Windows, we indicate that you need to pass additional flags (to the include and library dirs): https://pyogrio.readthedocs.io/en/latest/install.html#windows. Passing those additional flags gets complicated if not using ``python setup.py build_ext``, but eg pip, as noted in https://github.com/geopandas/pyogrio/issues/8
So this PR adds an alternative way to do this, by specifying environment variables. 
This is similar to how pygeos/shapely do it (eg https://github.com/pygeos/pygeos/blob/0835379a5bc534be63037696b1b70cf4337e3841/setup.py#L66-L72)
As a result, I can build locally on Windows with
```
set GDAL_INCLUDE_PATH=%CONDA_PREFIX%\Library\include
set …
```

Allow gdal config via GDAL_INCLUDE/LIBRARY_PATH env variables (Simplify building on Windows with environment variables)

---

docs/source/install.md
pyogrio/_err.pxd
pyogrio/_err.pyx
pyogrio/_ogr.pxd
pyogrio/_ogr.pyx
pyogrio/core.py

This follows the same approach as used by Fiona for searching for GDAL and PROJ data folders.
GDAL data folders are searched in the following precedence:
- wheel copy of gdal_data
- auto detection by GDAL (including `GDAL_DATA` env var)
- other well-known paths under `sys.prefix`
PROJ data folders are searched in the following precedence:
- wheel copy of proj
- default detection by GDAL (including `PROJ_LIB` env var)
- other well-known paths under `sys.prefix`

Search for GDAL and PROJ data folders during startup

---

pyogrio/_ogr.pyx
pyogrio/tests/test_core.py

Exposes check for valid GDAL / PROJ data file discovery to Python, and adds associated tests.
These should fail if GDAL and PROJ data are not correctly discovered by GDAL / PROJ.
In the case of PROJ, this verifies that PROJ data files are actually used, because it initializes a CRS object, which would fail if data files are not present.
In the case of GDAL data, this verifies that a [sentinal file is in the expected location](https://github.com/rasterio/rasterio/issues/1631#issuecomment-462395938).

Add direct tests for GDAL and PROJ data discovery

---

setup.py

With GDAL master, the reported version is 3.5.0dev, which breaks with the current setup.py

Update setup.py to allow building against GDAL master

---

.github/workflows/release.yml

Adds a specific test to the release builds to ensure that the source distribution can be successfully built (just using the GDAL container to keep this easy) and prevent future occurrences of broken sdist builds (xref #76).

CI: Add specific test for sdist

---

pyogrio/_geometry.pxd
pyogrio/_geometry.pyx
pyogrio/geopandas.py
pyogrio/tests/test_geopandas_io.py

Another small PR related to the discussions in https://github.com/geopandas/pyogrio/pull/75 and https://github.com/geopandas/pyogrio/pull/82. Regardless of the eventual outcome about what kind of default behaviour for inferring the geometry type we end up with, I think we will always want to give the option to overrule that by the user? 
So therefore this PR is already exposing the existing `geometry_type` keyword in the `write_dataframe` function (currently it only exists in the `pyogrio.raw.write(..)`.
(I was using this locally anyway to experiment with the geometry type impact)

ENH: expose geometry_type keyword in write_dataframe to manually set type

---

pyogrio/geopandas.py
pyogrio/tests/test_geopandas_io.py

Related to the discussion in https://github.com/geopandas/pyogrio/pull/75
This is a very simple change (not yet trying to detect if mixed geometries are truly mixed or only single/multi of the same type): if there is more than 1 geometry type, we create the GDAL dataset with "Unknown" geometry type ("Unknown" here is the slightly confusing name for "any" geometry type: *Use wkbUnknown if there are no constraints on the types geometry to be written.* from https://gdal.org/api/raster_c_api.html#gdal_8h_1a7f01d3d8584f29e4ef3c56b5af49d816) 
This is consistent with what Fiona (and therefore geopandas) currently does. 
And I would argue that this is also what GDAL does to some extent (although it is of course not exactly equivalent situation). If you start from a source like GeoJSON which does …

Correctly write mixed geometry types

---

pyogrio/_io.pyx
pyogrio/tests/test_geopandas_io.py

Follow-up on https://github.com/geopandas/pyogrio/pull/82 to give a more informative error message of the GDAL driver errors in case of mixed geometries

Propagate GDAL error message when geometry cannot be added to the layer

---

pyogrio/tests/test_geopandas_io.py

Fixes warning in the tests:
pyogrio/tests/test_geopandas_io.py::test_read_where_invalid[.gpkg]
/__w/pyogrio/pyogrio/pyogrio/raw.py:1[26](https://github.com/geopandas/pyogrio/runs/6164109003?check_suite_focus=true#step:6:26): UserWarning: Layer 'b'naturalearth_lowres'' does not have any features to read
result = ogr_read(

Fix "no features to read" warning in "test_read_where_invalid"

---

.github/workflows/release.yml
ci/environment.yml
pyogrio/_env.py
setup.py

Resolves #66
This makes `certifi` and installation requirement and follows approach from [Fiona #1095](https://github.com/Toblerity/Fiona/pull/1095) and [rasterio #2459](https://github.com/rasterio/rasterio/pull/2459)

Use certifi to set GDAL_CURL_CA_BUNDLE / PROJ_CURL_CA_BUNDLE defaults

---

.github/workflows/docker-gdal.yml

Resolves #107 
As I understand it, a recent pip upgrade now runs into issues with `oldest-supported-numpy` declared in `pyproject.toml` when running with `--no-build-isolation` when `numpy` isn't yet installed.  The fix is to add `--no-use-pep517`.
This updates to do the same thing as pandas: https://github.com/pandas-dev/pandas/pull/47015

Add --no-use-pep517 to get around pip oldest-supported-numpy issue

---

pyogrio/raw.py
pyogrio/tests/conftest.py
pyogrio/tests/test_geopandas_io.py
pyogrio/tests/test_raw_io.py

\+ add to file formats that should be tested.
Issue found: writing empty file to .geojsons is appartently not supported: logged here: #94

Add auto detection of driver for .geojson, .geojsonl and .geojsons files

---

docs/source/known_issues.md
pyogrio/_io.pyx
pyogrio/_ogr.pxd
pyogrio/tests/conftest.py
pyogrio/tests/fixtures/test_datetime.geojson
pyogrio/tests/test_raw_io.py

This came up in the geopandas tests. WIP: I still need to add a test for this (but because we don't yet have support for writing datetimes, that's a bit harder)

ENH: read DateTime fields with millisecond accuracy

---

pyogrio/core.py
pyogrio/raw.py
pyogrio/util.py

Currently we have the custom logic to also handle buffers or file-like objects inside `pyogrio.raw.read` (and thus used for `read_dataframe`), but `list_layers` only takes a string path, and `read_info` and `read_bounds` as well (although those will already prepare your string path into a vsi path). 
I think it can be useful to make this input path/buffer handling consistent for all read functions?

ENH: consistent handling of path or buffer in read functions

---

CHANGES.md
pyogrio/_io.pyx
pyogrio/tests/test_geopandas_io.py

Support writing object columns with np.nan values

---

pyogrio/tests/test_path.py

Resolves #116 
This splits out path tests to use the basic functions `raw.read`, `read_info`, `read_bounds` without GeoPandas being installed, and adds tests that use GeoPandas for each of those but marked to skip if GeoPandas is not present.  It is maybe a bit excessive to test all 3 basic functions every time, but not necessarily a bad thing.

TST: make sure that path tests run without geopandas

---

.github/workflows/docker-gdal.yml
.github/workflows/release.yml
.github/workflows/tests-conda.yml

This uses the [concurrency feature](https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#concurrency) of GH actions to cancel previous runs for a PR when a new commit comes in.  This may be useful for other projects that have longer-running test suites (e.g., Shapely, GeoPandas)

CI: Cancel jobs on subsequent push to PR

---

.github/workflows/lint.yml
.pre-commit-config.yaml
docs/source/install.md
pyogrio/__init__.py
pyogrio/_env.py
pyogrio/_version.py
pyogrio/core.py
pyogrio/raw.py
pyogrio/tests/test_core.py
pyogrio/tests/test_geopandas_io.py
pyogrio/tests/test_path.py
pyogrio/tests/test_raw_io.py
pyogrio/tests/win32.py
pyogrio/util.py
setup.cfg

This copies the linting CI step and pre-commit config from GeoPandas.  Includes auto-formatting using Black and manual updates to make Flake8 happy.
Note: all changes in `_version.py` are autoformatting and can be ignored.

CI: Enable linting on CI using GeoPandas configuration

---

CHANGES.md
pyogrio/geopandas.py
pyogrio/tests/test_geopandas_io.py

Resolves #114 
As discussed on 6/2/2022 GeoPandas dev team call; renaming for consistency throughout (`layer_geometry_type` was used only in geopandas I/O functions; `geometry_type` is used on other places).
Includes minor formatting cleanup of test file, sorry!

Rename layer_geometry_type to geometry_type

---

.github/workflows/tests-conda.yml
ci/environment-minimal.yml
pyogrio/tests/conftest.py
pyogrio/tests/test_geopandas_io.py

Supersedes #132 (thanks @jorisvandenbossche !)
Cleans up a dependency on pandas outside of our try / catch block for GeoPandas, and uses raw IO methods for preparing test files instead of geopandas

CI: Fix minimal test env and remove deps on pandas / geopandas

---

pyogrio/geopandas.py
pyogrio/tests/test_geopandas_io.py

Ran into this in the geopandas tests: currently if there is a missing geometry, we might either consider it as mixed instead of uniform geom type (which can error in case of Shapefiles) or take the `None` geometry type which then errors somewhere in our code expecting this keyword to be set.

BUG: fix geometry type inference in case of missing geometries

---

CHANGES.md
pyogrio/_io.pyx
pyogrio/_ogr.pyx
pyogrio/core.py

Resoves #144 
This moves driver registration to the import step.  We were not using it consistently across all internal functions, and this seemed the best way to make sure it was done up front and not repeated.

FIX: register drivers on import

---

.github/workflows/docker-gdal.yml

Editable installs are failing with latest version of pip due to presence of `pyproject.toml` file but without properly set version number.
This uses `--no-use-pep517` to sidestep some of the enforcement around recent python packaging standards.
Resolves build error noted in #146

CI: Fix tests on GDAL Docker container

---

CHANGES.md
pyogrio/_io.pyx
pyogrio/tests/test_raw_io.py

Bugfix: support writing NAT in datetime column

---

CHANGES.md
pyogrio/_io.pyx

As noted in #149 [comment](https://github.com/geopandas/pyogrio/issues/149#issuecomment-1221104056), we were calculating the count of features twice, which incurs extra and unnecessary overhead.  This removes that duplication.

FIX: Avoid duplicate count of features

---

.github/workflows/release.yml
.github/workflows/tests-conda.yml
ci/environment-libgdal3.5.1.yml
setup.py

GitHub deprecated macOS 10.15 runners; this updates to 11 but retains the build target of 10.15, so everything should still work as before.

BLD: fix library detection on Windows / CI: Upgrade macos runner from deprecated 10.15

---

.github/workflows/release.yml
docs/source/introduction.md
pyogrio/core.py
pyogrio/geopandas.py
pyogrio/raw.py
pyogrio/tests/conftest.py
pyogrio/tests/test_core.py
pyogrio/tests/test_geopandas_io.py
pyogrio/tests/test_raw_io.py

Resolves #162 
GDAL uses GEOS for intersection tests used by `bbox` filter when it is available, and falls back to a simple bounding box filter otherwise.
This updates the bbox tests to use a bbox that returns the same results regardless of whether GEOS is available or not.

CI/TST: Fix bbox tests to avoid breaking when GEOS is not available

---

benchmarks/conftest.py
benchmarks/test_raw_io_benchmarks.py

Small fixes to benchmarks:
* _read_ returns fids (as None) even when return_fids=False
* Duplicate dataset fixture in conftest
* Dataset fixture without file extension when using VSI

Benchmark fixes

---

ci/manylinux2014_x86_64-vcpkg-gdal.Dockerfile

Adding a similar workaround for https://github.com/microsoft/vcpkg/issues/27786 as the github action images do as well (https://github.com/actions/runner-images/discussions/6600, https://github.com/actions/runner-images/blob/6ef9c61220d9712317731cbdaa53bb0b25e73f94/images/linux/scripts/installers/vcpkg.sh#L16-L19)

CI: workaround vcpkg bug in linux wheel docker

---

README.md
ci/environment.yml
docs/source/conf.py
docs/source/install.md
pyogrio/tests/test_geopandas_io.py
pyogrio/tests/test_raw_io.py
setup.py

We don't strictly require pygeos, it's just best to use geopandas with pygeos under the hood. Updated the documentation to mention both pygeos or shapely>=2, ensured to have a test build with shapely 2 instead of pygeos, and updated some tests to be more generic (and not rely on pygeos). 
And also removed "pygeos" from the extra requirement.

DEPS: don't require pygeos + update to test with both pygeos and shapely 2

---

.github/workflows/release.yml
.github/workflows/tests-conda.yml
README.md
docs/source/install.md

Wheels are already built for 3.11, so updating docs and test CI as well.

CI: include Python 3.11 in test matrix

---

.github/workflows/docker-gdal.yml

Because just to be fun Github actions sometimes allow single or double quotes without caring, but for `if` expressions they [must be single quotes](https://docs.github.com/en/actions/learn-github-actions/expressions#literals).

CI: Fix GDAL docker github action

---

pyogrio/_io.pyx

Resolves #153.
Adapts the pattern for doing this in #155.
When `columns` are passed to `ogr_read`, any fields not requested to be read are set to be ignored by GDAL, which should reduce I/O when reading features from some drivers.

ENH: Ignore fields not in specified columns when reading features

---

pyogrio/_io.pyx
pyogrio/_ogr.pxd
pyogrio/_ogr.pyx
pyogrio/geopandas.py
pyogrio/raw.py
pyogrio/tests/test_geopandas_io.py
pyogrio/tests/test_raw_io.py

Closes https://github.com/geopandas/pyogrio/issues/177
This PR adds a minimal implementation of querying metadata items (based on https://github.com/Toblerity/Fiona/pull/950), not yet publicly exposed (we should do that as well at some point), but just enough to use internally.
We then use the metadata to check the dataset and layer creation options for the specific driver, so we can split the `**kwargs` in separate layer and dataset creation kwargs.

ENH: support dataset creation options (use metadata to split dataset/layer creation options)

---

pyogrio/_io.pyx
pyogrio/geopandas.py
pyogrio/raw.py
pyogrio/tests/test_raw_io.py

Closes https://github.com/geopandas/pyogrio/issues/122

Default to handle float NaN as null + add option to control it

---

CHANGES.md
pyogrio/_io.pyx
pyogrio/geopandas.py
pyogrio/raw.py
pyogrio/tests/test_arrow.py

Follow-up on https://github.com/geopandas/pyogrio/pull/155 to address the comment at https://github.com/geopandas/pyogrio/pull/155#pullrequestreview-1103120659 to add a raw IO function for pyarrow.Table (so without already the direct conversion to (geo)pandas). 
This PR adds a `read_arrow` function (and removing it as option from the numpy-based raw `read` function).

ENH: expose Arrow-based IO as read_arrow + doc

---

.github/workflows/docker-gdal.yml

Updates to latest 3.5 version and adds entry for latest 3.6 version

CI: Update GDAL versions in docker GDAL tests

---

.github/workflows/docker-gdal.yml
CHANGES.md
docs/source/introduction.md
pyogrio/_io.pyx
pyogrio/_ogr.pyx
pyogrio/geopandas.py
pyogrio/raw.py
pyogrio/tests/conftest.py
pyogrio/tests/test_core.py
pyogrio/tests/test_geopandas_io.py
pyogrio/tests/test_raw_io.py

Resolves #137 
This adds basic support to append additional records to existing layers when supported by the driver.
This uses driver metadata plus a known list of drivers to exclude in order to determine which drivers support write capability (and updates listing from `list_drivers()`), and raises errors when attempting to write to unsupported drivers.
This adds a specific GDAL version test when appending to FlatGeobuf to avoid segfaults due to https://github.com/OSGeo/gdal/issues/5739; anything prior to GDAL 3.5.1 appears to segfault.
I could not find a driver metadata key that indicates if a driver supports append capability.  Rather than try to maintain a list of known drivers that support append, I think we probably just need to let GDAL raise the errors when a given driver / GDAL …

ENH: Add append support to write functions

---

pyogrio/_io.pyx
pyogrio/_ogr.pxd
pyogrio/raw.py
pyogrio/tests/test_raw_io.py

OpenFileGDB now supports write from GDAL 3.6.0 onwards, but does not support transactions.  We were always assuming transaction support was present because it was available for all drivers we specifically tested previously (though GDAL makes clear not all datasets / layers support transactions).
This adds a check for that capability and creates features without a transaction if layer doesn't support them, and adds a test to ensure that we can write OpenFileGDB correctly now.

FIX: Only use transactions when writing features if layer supports them

---

CHANGES.md
pyogrio/_io.pyx

Closes #207
The diff looks messy, but the only thing that it did was putting a `try: ... finally: ...` around each block that deals with a feature (as we already did in the writing path).

Fix memory leak in reading data

---

CHANGES.md
pyogrio/geopandas.py
pyogrio/raw.py
pyogrio/tests/test_geopandas_io.py

closes #222
apparently closes #121 as well

ENH: add automatic detection of 2.5D in write_dataframe

---

CHANGES.md
pyogrio/_io.pyx
pyogrio/core.py
pyogrio/geopandas.py
pyogrio/raw.py
pyogrio/tests/fixtures/test_nested.geojson
pyogrio/tests/test_core.py
pyogrio/tests/test_geopandas_io.py

Resolves #216 
This adds basic support for dataset read options to `read(...)`, `read_dataframe(...)`, and `read_info(...)`.  
Because we don't know the driver until after GDAL opens the dataset, it is hard to validate the options ourselves.  GDAL raises warnings to stderr for invalid options, which we can't capture.

ENH: Add support for dataset read options

---

pyogrio/_io.pyx

To avoid warnings like
```
pyogrio/_io.c: In function ‘__pyx_pf_7pyogrio_3_io_10ogr_write’:
pyogrio/_io.c:23290:13: warning: case label value is less than minimum value for type
23290 |             case wkbPolygon25D:
|             ^~~~
pyogrio/_io.c:23260:13: warning: case label value is less than minimum value for type
23260 |             case wkbLineString25D:
|             ^~~~
...
```
Without the cast to int, I suppose `wkbtype` in interpreted as a `char` by cython, which is a single byte (so only range of int8), while some of the wkb types defined in the enum in GDAL are big integers: https://github.com/jorisvandenbossche/gdal/blob/481966e5099057d8cada051e036ae00dcb4af485/ogr/ogr_core.h#L406-L520
(in practice it seems to work though, since we can write 3D geometries, so it's just …

Fix compile warning for OGRwkbGeometryType enum case

---

CHANGES.md
docs/source/known_issues.md
pyogrio/_geometry.pyx
pyogrio/geopandas.py
pyogrio/tests/test_core.py
pyogrio/tests/test_geopandas_io.py

Resolves #225
This standardizes from `2.5D <type>` to `<type> Z` for geometry type labels.

ENH: Standardize 2.5D => Z in geometry type labels

---

CHANGES.md
pyogrio/_io.pyx
pyogrio/geopandas.py
pyogrio/raw.py
pyogrio/tests/test_geopandas_io.py
pyogrio/tests/test_raw_io.py

Closes https://github.com/geopandas/pyogrio/issues/219
The required change in cython to suppport passing a mask is actually quite limited, it's mostly new code in geopandas.py to get the proper data/mask.

ENH: support mask for missing values when writing data / support writing pandas nullable dtypes

---

pyogrio/tests/test_geopandas_io.py

Pandas 2.0 was released, so our CI started to fail. 
We might want to add some various versions of (geo)pandas to the different CI builds, because right now basically all builds were failing, indicating they are all using pandas 2.0 already (except the one minimal build without (geo)pandas)

TST: fix datetime test for pandas 2.0 (preserves ms resolution)

---

CHANGES.md
pyogrio/_err.pyx
pyogrio/core.py
pyogrio/geopandas.py
pyogrio/raw.py
pyogrio/tests/conftest.py
pyogrio/tests/test_core.py
pyogrio/tests/test_geopandas_io.py
pyogrio/tests/test_raw_io.py

Follow-up on https://github.com/geopandas/pyogrio/pull/236, xref https://github.com/geopandas/pyogrio/issues/91#issuecomment-1485913484

 ENH: raise Python warnings instead of printing to stderr for GDAL Warning messages

---

pyogrio/tests/test_geopandas_io.py

GDAL 3.6.4 includes changes to the FlatGeobuf driver that disallows writing null / empty geometries when also writing a spatial index (the default).
This updates the failing test to strip those out before writing.
This fixes the failing tests for latest GDAL.

TST: Fix write of FlatGeobuf for empty / null geometries for GDAL >= 3.6.4

---

CHANGES.md
pyogrio/_io.pyx
pyogrio/_ogr.pxd
pyogrio/geopandas.py
pyogrio/tests/test_arrow.py

BUG: Fix `fid_as_index=True` doesn't set fid as index `read_dataframe` with `use_arrow=True`

---

CHANGES.md
pyogrio/_io.pyx
pyogrio/_ogr.pyx
pyogrio/geopandas.py
pyogrio/raw.py
pyogrio/tests/test_core.py
pyogrio/tests/test_geopandas_io.py
pyogrio/tests/test_raw_io.py

ENH: support writing dataframes without geometry column

---

CHANGES.md
pyogrio/_io.pyx
pyogrio/geopandas.py
pyogrio/tests/test_arrow.py
pyogrio/tests/test_geopandas_io.py
pyogrio/tests/test_raw_io.py

Necessary changes and tests to ensure following behaviour for both `use_arrow=True` and `use_arrow=False`:
* if `columns=[]`, `read_geometry=False` and `return_fid/fid_as_index=False`, a ValueError is raised
* if `columns=[]`, `read_geometry=False` and `return_fid/fid_as_index=True`, the index is read and returned
* if none of the above, but `fid_as_index=False` and the result ends up having no geometry nor attribute columns (eg. because the input file doesn't have a geometry column and `columns=[]`), an empty DataFrame is returned.
closes #263

Raise error if function is used with parameters to read no geometry, columns, or fids

---

docs/source/introduction.md
pyogrio/geopandas.py
pyogrio/raw.py
pyogrio/tests/test_geopandas_io.py

reference #276
Note: for the links to external pages in the inline documentation, I had to put newlines around the links below, otherwise ".." is placed at the end of them and then most don't work anymore as intended.
For reference, this is the script used to test what the documentation should contain:
``` python
from pathlib import Path
import warnings
import pyogrio
warnings.simplefilter("ignore")
url_shp = "https://github.com/theroggy/pysnippets/raw/main/pysnippets/pyogrio/polygon-parcel_31370.zip"
url_gpkg = "https://github.com/geofileops/geofileops/raw/main/tests/data/polygon-parcel.gpkg"
wheres = [
None,
"LBLHFDTLT LIKE 'Gras%'",
"LBLHFDTLT LIKE 'gras%'",
"LBLHFDTLT ILIKE 'gras%'",
"LBLHFDTLT NOT LIKE 'Gras%'",
"LBLHFDTLT != 'Grasklaver'",
"LBLHFDTLT IN ('Hoofdgebouwen', …
```

DOC: improve doc of where param

---

.github/workflows/docker-gdal.yml
.github/workflows/release.yml
CHANGES.md
README.md
ci/environment-libgdal3.5.1.yml
ci/environment-minimal.yml
ci/requirements-wheel-test.txt
docs/source/install.md
docs/source/introduction.md
environment-dev.yml
pyogrio/_compat.py
pyogrio/core.py
pyogrio/geopandas.py
pyogrio/raw.py
pyogrio/tests/conftest.py
pyogrio/tests/test_arrow.py
pyogrio/tests/test_geopandas_io.py
pyogrio/tests/test_raw_io.py
setup.py

This raises the minimum supported version of GDAL to 3.5.* (note: no compatibility change, just dropping old versions from CI).
This updates the CI matrix to use newer Docker images from ghcr.io (current home of GDAL images).
This adds `_compat.py` to check the state of optional dependencies and GDAL features like Arrow API or GEOS.  This will give us a place in later PRs to set variables to use Arrow by default.
This drops shim to use PyGEOS; otherwise the conditional presence of it was cluttering up tests esp. those around #285.  While GeoPandas support should continue to work with PyGEOS instead of Shapely 2.0, we no longer test that specifically and no longer list that as a compatible setup.  The tests assume that if GeoPandas is present that Shapely >= 2.0 is present.
This adds a new …

TST: drop older GDAL, require shapely for tests, consolidate arrow test parametrize

---

.github/workflows/docker-gdal.yml
CHANGES.md
docs/source/introduction.md
pyogrio/_io.pyx
pyogrio/geopandas.py
pyogrio/raw.py
pyogrio/tests/test_arrow.py
pyogrio/tests/test_geopandas_io.py
pyogrio/tests/test_raw_io.py

Progress toward feature parity between Arrow and non-Arrow read interfaces.
This adds support for `skip_features` and `max_features` to `read_arrow`, which enables these to be passed through via `read_dataframe(path, use_arrow=True, skip_features=10, max_features=2)` so that the behavior is the same with and without `use_arrow`.
I added a note to the introduction to describe the overhead involved:`use_arrow` is `True`, `skip_features` and `max_features` will incur additional overhead because all features up to the next batch size above `max_features` (or size of data layer) will be read prior to slicing out the requested range of features. If `max_features` is less than the maximum Arrow batch size (65,536 features) only `max_features` will be read. All features up to `skip_features` are …

ENH: Add support for skip_features, max_features for read_arrow

---

CHANGES.md
pyogrio/_io.pyx
pyogrio/tests/test_core.py
pyogrio/tests/test_geopandas_io.py
pyogrio/tests/test_raw_io.py

Resolves #294 
Removes the `UserWarning` warning previously raised when no features were read from the data source.

ENH Remove warning on no features

---

pyogrio/tests/test_geopandas_io.py

Starting to parametrize some more tests (xref https://github.com/geopandas/pyogrio/issues/278). 
Discovered one issue with invalid SQL WHERE attribute filter not raising an error for GPKG (https://github.com/OSGeo/gdal/issues/8492)

TST: expand testing with Arrow reader

---

pyogrio/_io.pyx
pyogrio/raw.py
pyogrio/tests/test_arrow.py
pyogrio/tests/test_core.py
pyogrio/tests/test_geopandas_io.py
pyogrio/tests/test_raw_io.py

This sidesteps making a decision around implementing support for negative `skip_features` in #309 for now and simply disallows that, which would have been equivalent to the behavior prior to #282.  We can add support for negative slicing at a different time, if we so choose.
This raises a specific `ValueError` and expands tests to match.  I also added checks for negative `max_features` and associated tests.

FIX: Disallow negative skip_features

---

pyogrio/_io.pyx
pyogrio/core.py
pyogrio/tests/test_raw_io.py

As most drivers seem to support this, it might be practical to suggest this option when a file cannot be opened?
For writing, the driver detection doesn't support this at the moment, and gdal doesn't seem to support this either for writing... so where it is probably easier to just keep using the `driver` parameter.
reference #310

DOC: mention option of prefixing a path with the driver in ogr_open exception 

---

CHANGES.md
pyogrio/util.py

See https://github.com/geopandas/pyogrio/issues/316#issuecomment-1780574589, this avoids adding it as an actual dependency.

Avoid usage of packaging in non-test code

---

CHANGES.md
pyogrio/util.py
setup.py

Reverses #318
Tested binary wheel in a brand new virtual environment, and it installed `packaging` and appeared to work correctly.

Add packaging as an install dependency

---

CHANGES.md
pyogrio/geopandas.py
pyogrio/tests/test_geopandas_io.py

FIX: Fix error in `write_dataframe` if input has a date column and non-consecutive index values

---

SECURITY.md
docs/source/install.md

Resolves #311
Loosely inspired by [Fiona #1308](https://github.com/Toblerity/Fiona/pull/1308).
This is perhaps a bit on the verbose side, but I was trying to provide sufficient content in regards to 3rd party dependencies, since that is where the majority of the vulnerabilities are likely to occur.
Notably absent is what our follow-up timeframe is, since I didn't want to obligate us to follow a specific response protocol or timeframe.  Rather, we can refine that protocol on a case by case basis depending on the nature of vulnerabilities as they are reported.

Add security policy

---

.github/workflows/docker-gdal.yml
README.md
docs/source/install.md

- Update to GDAL 3.7.3 as I'd like to be able to test a backport to this version in GDAL regarding sql statements + arrow
- Add GDAL 3.8.1 container to have latest released version of GDAL tested

CI: add gdal 3.8.1 tests + update gdal 3.7.2 to 3.7.3

---

docs/source/install.md
environment-dev.yml

There are quite some new features that are depending on GDAL 3.8, so seems logical to use GDAL 3.8 during development...

MNT: use gdal 3.8.3 in environment-dev.yml

---

.gitignore
.pre-commit-config.yaml
Pipfile
docs/source/install.md
environment-dev.yml
pyogrio/tests/test_geopandas_io.py
pyogrio/tests/test_path.py
pyogrio/tests/win32.py
pyogrio/util.py
pyproject.toml
setup.cfg
setup.py

Resolves #341 
Similar to changes in [GeoPandas #2921](https://github.com/geopandas/geopandas/pull/2921) but without needing to configure additional rules.

MNT: Switch from flake8 to ruff for linting

---

pyogrio/_io.pyx
pyogrio/tests/test_geopandas_io.py

Addressing test failures with GDAL main caused by https://github.com/OSGeo/gdal/pull/9114. 
(to be honest, being a non-native speaker, but "_as being_ in a file format" sounds very strange to my ears)

TST: update error message in tests for GDAL 3.9

---

pyogrio/core.py

Corrected key "geometry" to "geometry_type" in docstring for pyogrio.io.read_info() method. #357

DOC: Correct key name in pyogrio.read_info() docstring 

---

CHANGES.md
pyogrio/_io.pyx
pyogrio/tests/test_arrow.py

Resolves half of https://github.com/geopandas/pyogrio/issues/345. @jorisvandenbossche mentioned in https://github.com/geopandas/pyogrio/issues/345#issuecomment-1909638656 that he'd suggest making the change to geoarrow metadata. I'd also propose that we make this the default.
A test is added to verify that the metadata on the geometry field is set. The name should be `geoarrow.wkb` and the extension metadata should include a CRS field with PROJJSON, which I assert is EPSG:4326 for this test dataset.
@brendan-ward would you still prefer having a flag for the user to set this? Ref https://github.com/geopandas/pyogrio/issues/345#issuecomment-1908878875

Read with GeoArrow metadata for GDAL >= 3.8

---

pyogrio/geopandas.py

I don't know how I missed this in #253, but there's a logical error if an exception is thrown in this block.
I'm not quite sure how to test this - I only noticed the error in my geopandas dev environment where I had pyogrio 0.7.2 with pandas dev - so I was getting the exception fixedby #348 (not part of 0.7.2), not a future error due to  mixed time zones - which is what this try except was originally for.

BUG: undefined variable in timezone logic

---

pyogrio/_io.pyx
pyproject.toml
setup.py

Currently, we do have _build_ dependency on numpy (listed in pyproject.toml's `build-system.requires`), but in practice I don't think we are actually using anything from numpy's C API, as far as I can see. 
Having numpy as a build dependency adds some complexity, especially with ABI compatibility of buildtime vs runtime version of numpy (in the past you needed to build with an older version, now with numpy 2.0 we need to build with the latest to ensure to be compatible with both numpy 1.x and 2.0). If we don't actually need numpy at compile time, removing that makes this a lot simpler and we don't have to worry about those issues.

BLD: remove numpy as build depedency (only required run dependency)

---

CHANGES.md
pyogrio/_io.pyx
pyogrio/tests/test_geopandas_io.py
pyogrio/tests/test_raw_io.py

I noticed in some [geofileops tests](https://github.com/geofileops/geofileops/actions/runs/8110958569/job/22169297289?pr=505) that using pyogrio to write/read dataframes to ".csv" files gives encoding issues.
This PR fixes those.
Odd detail: I only saw this behaviour on the github CI windows systems: locally I couldn't reproduce. Apparently:
- when running tests on my local windows `locale.getprefferedencoding()` returns "UTF-8", even though when I run `locale.getprefferedencoding()` in a seperate script it returns the typical one for windows: "cp1252".
- in the tests on the github windows machines, `locale.getprefferedencoding()` returns "cp1252".

BUG: fix encoding issues on windows for some formats

---

CHANGES.md
pyogrio/_compat.py
pyogrio/_io.pyx
pyogrio/core.py
pyogrio/tests/test_core.py

Add some properties to read_info that I regularly use: layer_name, fid_column and geometry_name.

ENH: add some missing properties to read info

---

pyogrio/tests/test_geopandas_io.py

Tested this in the context of documenting known difference between Fiona and Pyogrio... so better to add it to the test permanently.
Or... based on feedback in https://github.com/geopandas/geopandas/pull/3206 is this something that works by accident and isn't supposed to, or not guaranteed that it will keep working?

TST: add test case to write GeoDataFrame without geometry column

---

CHANGES.md
pyogrio/_io.pyx
pyogrio/raw.py
pyogrio/tests/test_arrow.py
pyogrio/tests/test_geopandas_io.py

Resolves #350
Moves the test for bool cols into the Cython tier where we can also check the driver and ignored fields, so that we only raise the exception when reading FlatGeobuf/GPKG if also reading a bool col

FIX: Only raise GDAL <3.8.3 bool I/O exception for FlatGeobuf / GPKG 

---

CHANGES.md
pyogrio/geopandas.py
pyogrio/tests/test_arrow.py
pyogrio/tests/test_geopandas_io.py
setup.cfg

Follow-up on https://github.com/geopandas/pyogrio/pull/346 to expose the Arrow-based writing through geopandas-based `write_dataframe` as well.
Updated our geopandas writing tests to be parametrized on `use_arrow` for writing as well. This didn't catch any issues with the `write_arrow` itself, but we needed to do some pre-processing to handle the promotion to multi types consistently (as in the normal write path, this happens per geometry inside `ogr_write`)
There are a few things that don't work with Arrow:
- No support (yet) for writing without a geometry column
- ~~No support (yet) for writing an all-missing geometry column (the conversion from pandas to Arrow then doesn't result in the correct type, something that could be fixed in the pre-processing)~~ -> add that in the …

ENH: allow using Arrow writing in pyogrio.write_dataframe (use_arrow=True option)

---

CHANGES.md
pyogrio/_io.pyx
pyogrio/_ogr.pxd
pyogrio/_ogr.pyx
pyogrio/geopandas.py
pyogrio/raw.py
pyogrio/tests/conftest.py
pyogrio/tests/test_arrow.py
pyogrio/tests/test_core.py
pyogrio/tests/test_geopandas_io.py
pyogrio/tests/test_path.py
pyogrio/tests/test_raw_io.py
pyogrio/util.py

Resolves https://github.com/geopandas/pyogrio/issues/249
This enables basic writing to memory using an `io.BytesIO` object.  This does not currently support append / adding layers; I tried working that out unsuccessfully in earlier commits, but we could return to this in a later PR.  It seems like it should be possible in theory.
This specifically blacklists ESRI Shapefile and OpenFileGDB because they write multiple files, which can't be returned successfully as a single memory file.

ENH: enable support for writing to memory

---

pyogrio/geopandas.py
pyogrio/raw.py
pyogrio/tests/test_arrow.py
pyogrio/tests/test_geopandas_io.py

It seems that in the final version of the `ogr_write_arrow` actually already could write data without a geometry column, but I didn't test that anymore, and so all what is needed to allow this was to clean up our validation of the keywords.

ENH: allow writing without geometry using Arrow

---

docs/source/api.rst
pyogrio/__init__.py

Given that those are less low-level as the "raw" `read`/`write` functions, I think it would make sense to expose those top-level?

Expose the Arrow read and write function top-level

---

CHANGES.md
pyogrio/_io.pyx
pyogrio/_ogr.pyx
pyogrio/_vsi.pxd
pyogrio/_vsi.pyx
pyogrio/core.py
pyogrio/raw.py
pyogrio/tests/conftest.py
pyogrio/tests/test_arrow.py
pyogrio/tests/test_core.py
pyogrio/tests/test_path.py
pyogrio/util.py
setup.py

Resolves #401 
This moves all handling of creation / destruction of the in-memory dataset used for read operations to the Cython tier, and now passes in either a string or bytes to `read_info()`, `list_layers()`, `read_bounds()`, `read()`, `read_arrow()` functions.  I think this also sets us to for later refactors where we may pass file-like / filesystem-like objects directly down to Cython in order to use the GDAL virtual filesystem plugin.
To keep things organized, I split VSI related Cython functions into the new `_vsi.pyx` / `_vsi.pxd` files.
Because the bytes buffer is passed as a parameter, it remains in scope during the Cython function and we don't need to hold an extra handle on it like before. (the handle was required to prevent Python from deallocating it while GDAL still may …

ENH: refactor handling of reading from in-memory dataset

---

CHANGES.md
pyogrio/tests/test_path.py
pyogrio/util.py

This is an upstream equivalent of https://github.com/geopandas/geopandas/pull/3280 to fix https://github.com/geopandas/geopandas/issues/3279 which is an edge case to do with using urlparse in detecting file schemes.

BUG: Fix hash url parsing

---

CHANGES.md
pyogrio/_io.pyx
pyogrio/_ogr.pxd
pyogrio/tests/test_geopandas_io.py

Closes #420
My cython is atrocious.
Followed what was done in fiona, qgis and gdal documentation to find this is probably what needs to be done. But I am probably doing it too broadly and may have unintended consequences in other filetypes.
~Still need to write tests.~
Need to investigate how this may impact other file types.

BUG: fix write of kml lon/lat transpose

---

CHANGES.md

Apologies, I had incorrectly entered the fix for #421 under v0.8.0 in my PR. This PR fixes that in the changelog

Fix #421 entry in changelog from v0.8.0 to 0.9.0

---

CHANGES.md
pyogrio/geopandas.py
pyogrio/tests/test_geopandas_io.py

Closes #432
Add TODO note to sort-out reading `POINT EMPTY`, which I'll open in a separate issue...

FIX: silence warning from write_dataframe with GeoSeries.notna()

---

CHANGES.md
pyogrio/_io.pyx
pyogrio/tests/test_raw_io.py

Without this change, when a `bbox` or `mask` is passed in and the geometry is ignored, the filter excludes all rows and an empty response is returned.

BUG: Enable mask & bbox filter when geometry column not read

---

.github/workflows/docker-gdal.yml

This adds [uv](https://github.com/astral-sh/uv) for faster pip installs and uses a virtual environment that it manages to get around virtual environment errors on latest GDAL.
We were previously getting this from GDAL-latest, and the easiest way it seemed to work around this was to use a dedicated virtual environment:
```
Run python3 -m pip install --no-cache-dir -U pip wheel
error: externally-managed-environment
× This environment is externally managed
╰─> To install Python packages system-wide, try apt install
python3-xyz, where xyz is the package you are trying to
install.
If you wish to install a non-Debian-packaged Python package,
create a virtual environment using python3 -m venv path/to/venv.
Then use path/to/venv/bin/python and path/to/venv/bin/pip. Make
sure you have python3-full …
```

CI: Use uv for faster pip installs, fix venv issues in latest GDAL

---

CHANGES.md
pyogrio/tests/conftest.py
pyogrio/tests/test_arrow.py
pyogrio/tests/test_core.py
pyogrio/tests/test_raw_io.py
pyogrio/util.py

Since 0.8.0 reading a zstandard compressed file does not work anymore. The following code works in 0.7.2, but not in 0.8.0 and 0.9.0:
``` python
import geopandas as gpd
import zstandard
import io
gdf = gpd.GeoDataFrame(geometry=[Point(4, 2), Point(4, 2)])
gdf.to_file('uncompressed.geojson', driver='GeoJSON')
with open('uncompressed.geojson', 'rb') as ro:
content = ro.read()
compressed_content = zstandard.compress(content)
with open('compressed.geojson.zst', 'wb') as w:
w.write(compressed_content)
with open('uncompressed.geojson', 'rb') as fh:
mem = io.BytesIO(fh.read())
gdf = gpd.read_file(mem)
print(gdf)
with open('uncompressed.geojson', 'rb') as fh:
gdf = gpd.read_file(fh)
print(gdf)
with open('compressed.geojson.zst', 'rb') as fh:
dctx = zstandard.ZstdDecompressor()
with …
```

Fix reading from zstd decompression stream

---

CHANGES.md
pyogrio/geopandas.py
pyogrio/raw.py
pyogrio/tests/test_arrow.py
pyogrio/tests/test_geopandas_io.py
pyogrio/tests/test_raw_io.py

As indicated in #430 and [geopandas #3369](https://github.com/geopandas/geopandas/discussions/3369), if a user passed an open file handle to write, we were failing with confusing error messages.  While the docstrings in pyogrio specify the allowed inputs, we weren't strictly verifying those, and so any path that was not BytesIO was first getting cast to a string, and then failing badly from there.
These usages worked for users with the Fiona engine (previous default) in GeoPandas, so it is proving to be a point of confusion now that Pyogrio is the default engine and things are no longer working as expected.
In most cases, writing the dataset to BytesIO and then writing those bytes to the file handle (regular file handle via `open`, an fsspec opened file handle, or an open handle within a …

FIX: Raise NotImplementedError if user passes an open file handle to write

---

pyogrio/tests/test_core.py
pyogrio/tests/test_raw_io.py

We were already using `requires_shapely` test mark for several tests, but not tests that used the `mask` parameter.

TST: Consolidate test marks that skip if shapely is not installed

---

.github/workflows/tests-conda.yml

The caching results in older depencencies being used for long times, so incompatibilities with new versions not raised asap.
Reference https://github.com/geopandas/pyogrio/pull/452, where conda tests keep failing as the newest version of shapely, 2.0.6 , is not picked up due to the caching. In this PR shapely 2.0.6 is immediately picked up.

CI: disable caching of conda env so most recent versions of dependencies are used

---

CHANGES.md
ci/envs/latest.yml
ci/envs/minimal.yml
ci/envs/nightly-deps.yml
environment-dev.yml
pyogrio/_compat.py
pyogrio/geopandas.py
pyogrio/tests/conftest.py
pyogrio/tests/test_geopandas_io.py
pyogrio/tests/test_path.py

Switch to `libgdal-core` as dependency instead of `libgdal`. This package is significantly smaller as it doesn't contain some large GDAL plugins. Extra plugins can be installed as seperate conda packages if needed: more info [here](https://gdal.org/download.html#conda).
This PR also removes the `pyogrio` dependency on `pyproj`, as `pyproj` is not part of `libgdal-core` nor `geopandas` since `geopandas 1.0`: closes #456
Reference https://github.com/conda-forge/pyogrio-feedstock/issues/48

MAINT: change conda dependency to libgdal-core + remove dependency on pyproj

---

.github/workflows/docker-gdal.yml
.github/workflows/lint.yml
.github/workflows/tests-conda.yml

I noticed the tests run even if the linting fails, which not needed.
This PR changes this so the lint workflow triggers both test workflows if the linting is ready.

MAINT: avoid tests to run if linting fails

---

.github/workflows/docker-gdal.yml
pyproject.toml

I recall `wheel` being listed in instructions somewhere (maybe for `setuptools`), but it wasn't, and isn't, necessary.

Remove unnecessary build requirement

---

setup.py

The Cython files are private (`_`-prefixed), so probably shouldn't be used by downstreams.

Exclude development files from wheels

---

ci/manylinux2014_x86_64-vcpkg-gdal.Dockerfile
ci/manylinux_2_28_aarch64-vcpkg-gdal.Dockerfile

I know this is also being handled in https://github.com/geopandas/pyogrio/pull/451, but I _think_ that simply updating the docker images might be sufficient to at least get green CI in the meantime

BLD: update docker image tags for linux wheel building

---

pyproject.toml
setup.py

This moves the generic project settings to the `pyproject.toml` `[project]` table, for now leaving setuptools specific ones in the setup.py file.
All info is just moved 1:1, except for the few things I commented about below.
I built the sdist and wheel locally, and that looked all good.

MAINT: move generic project settings to pyproject.toml

---

docs/source/install.md

Resolves #472, obviates #378.
It is potentially a bit confusing while we're still using `libgdal` on conda-forge, but I think these may need to be installed once we switch to `libgdal-core`.

DOC: Add install note re: advanced drivers on conda-forge

---

.github/workflows/release.yml

We have Python 3.13 wheels now, but we were not yet testing them. Not all (optional) dependencies already have releases supporting Python 3.13, but we can already test with the minimal set of dependencies.

BLD: test the Python 3.13 wheels

---

docs/source/introduction.md

Depends on #457
Adds examples using the automatically-managed in-memory dataset as well as externally managed `/vsimem/` datasets.

DOC: Add docs for working with in-memory datasets

---

pyogrio/tests/test_geopandas_io.py

I wonder if there is any use in delaying the release for this. It will have to be solved upstream... and pyogrio 0.9 with GEOS 3.13 has the same problem...
So, just skipping the test might be OK for now?
Reference: https://github.com/geopandas/pyogrio/issues/478

TST: skip multisurface test with arrow to avoid crash

---

.github/workflows/tests-conda.yml
ci/envs/libgdal3.5.1.yml

The windows conda-forge test runner fails for the `libgdal3.5.1` env when using `pip` to install shapely.  It looks like an issue with where the mamba executables are installed.

CI: Try to resolve mamba install issue on windows when using with pip

---

README.md

The pyogrio introduction was slightly dated in some locations, so I started off with doing some minor updates.
However, I got a bit carried away with making small changes here and there... I also changed the order of some blocks of text, which doesn't help to see the exact changes applied :-(.
For the "vectorized", not sure why this term was used, but I don't think it is really relevant for what happens in pyogrio, or possibly I'm just wrong on that?
Anyway, if it's not an improvement, just say so, a PR is easy to delete again ;-) (or rather, to close without merging).

DOC: update pyogrio introduction

---

pyogrio/tests/test_geopandas_io.py

Fixes #488
Note: I did *not* actually test against GDAL 3.10. Hopefully my guess for why it fails is right, and hence this should fix it

TST: test_write_kml_file_coordinate_order(): make it compatible with GDAL 3.10

---

.github/workflows/docker-gdal.yml
.github/workflows/release.yml

The latest uv release changed where the binary got installed (https://github.com/astral-sh/uv/issues/8911, https://github.com/astral-sh/uv/releases/tag/0.5.0)

CI: update for uv 0.5

---

.circleci/config.yml
.github/workflows/docker-gdal.yml
.github/workflows/release.yml
.github/workflows/tests-conda.yml
CHANGES.md
ci/manylinux2014_x86_64-vcpkg-gdal.Dockerfile
ci/manylinux_2_28_aarch64-vcpkg-gdal.Dockerfile
ci/manylinux_2_28_x86_64-vcpkg-gdal.Dockerfile
ci/vcpkg.json
pyproject.toml
setup.py

MNT: Upgrade to GDAL 3.10.0

---

CHANGES.md
pyogrio/_io.pyx

`shapely.to_wkb` (called in `pyogrio.geopandas.write_dataframe` via `geopandas.array.to_wkb`) defaults to machine byte order, so simply reading the first byte (of a 4-byte integer geometry type) is broken on big-endian machines. And since some geometry type could be 2 bytes, this also seems broken on little-endian machines, though I did not check if any 2-byte types could be produced.
The commented-out code here indicates the correct course of action (reading the first byte to determine byte order).
This fixes the 190 tests that go through this function and fail on big-endian.

Fix WKB writing on big-endian systems

---

CHANGES.md
pyogrio/_compat.py
pyogrio/_err.pxd
pyogrio/_err.pyx
pyogrio/_geometry.pyx
pyogrio/_io.pyx
pyogrio/_ogr.pxd
pyogrio/_ogr.pyx
pyogrio/tests/conftest.py
pyogrio/tests/test_geopandas_io.py

This was present in Rasterio (https://github.com/rasterio/rasterio/pull/2526) and has been included in fiona::_err recently (https://github.com/Toblerity/Fiona/pull/1408)... so this PR is based on the change there.
Closes #491

ENH: capture all errors logged by gdal when opening a file fails

---

.github/workflows/release.yml

Resolves #504 
Note: this is the last MacOS runner that supports x86_64; MacOS >= 14 is Arm64 only.  (not that we have any control over that, just mentioning it)

CI: Upgrade to MacOS 13 runner

---

ci/vcpkg.json

I am running into the issue that pyogrio (or geopandas with the pyogrio engine) cannot read  a file from Google Cloud Storage. 
I get intermittently either a `DataSourceError: CPLRSASHA256Sign() not implemented: GDAL must be built against libcrypto++ or libcrypto (openssl)` or `DataSourceError: HTTP response code: 403`. 
This is specifically with the wheels (with conda it works), and using fiona it also works. The first error message seems to indicate we don't properly built with openssl, although vcpkg _does_ install openssl. For the Fiona wheels (and the conda libgdal), I can verify with `ldd` that the libgdal.so included in the wheel is linking against libcrypto (which comes from openssl). For our own wheel I can't check that the same way because we statically link the gdal …

BLD/RLS: ensure wheels are including GDAL built with openssl

---

pyproject.toml

I noticed some warnings locally about conflicting "D" rules, and that seems to go away when specifying the style we use -> https://docs.astral.sh/ruff/settings/#lint_pydocstyle_convention

LINT: indicate numpy docstrings for ruff pydocstyle rules

---

ci/envs/latest.yml

We don't need/use the full pyarrow... and since pyarrow 16 there is a "pyarrow-core" available on conda.
Number of skipped tests stays the same...

CI: use pyarrow-core as dependency in tests

---

CHANGES.md
pyogrio/_compat.py
pyogrio/_io.pyx
pyogrio/tests/test_geopandas_io.py

BUG: fix writing fids to e.g. GPKG file with use_arrow

---

.github/workflows/docker-gdal.yml

This updates the docker tests to use the `setup-uv` action for installing `uv` instead of installing manually ourselves.  This matches the way it installed in the release workflow.

CI: Use setup-uv action in docker tests

---

pyogrio/geopandas.py

Preparing the data in numpy arrays is not needed for `use_arrow=True`, so move a block of code to avoid the unneeded processing.

ENH: avoid redundant processing in write_dataframe with use_arrow

---

ci/envs/nightly-deps.yml

Up to now, the nightly gdal is not used in the conda environment for this test. Probably better to also use the master/nightly version of GDAL in this test?
Remark: there is also a test using the latest gdal docker image... which is also typically a master/nightly version of gdal that is used.

CI: also use gdal nightly in nightly-deps tests

---

pyogrio/tests/test_core.py

GDAL 3.11 retires quite some drivers... and apparently the .txt ext doesn't have multiple drivers anymore, so remove it from the test.

TST: changes in tests to pass GDAL 3.11 (nightlies)

---

pyogrio/_compat.py
pyogrio/geopandas.py
pyogrio/tests/test_geopandas_io.py

Document and test the extra option "fix" for the `on_invalid` parameter of `read_dataframe` made possible in shapely 2.1.
resolves #423

DOC/TST: document and test read_dataframe with on_invalid=fix

---

CHANGES.md
pyogrio/geopandas.py
pyogrio/tests/test_geopandas_io.py

When a dataframe is being written with an object column without any rows or with only None values in the object column, the object column is converted to an null type arrow column, which is not supported by gdal and leads to an error being thrown.
Fixes #513

BUG: fix error in write_dataframe when writing an empty or all-None object column with use_arrow

---

CHANGES.md
pyogrio/geopandas.py
pyogrio/tests/test_geopandas_io.py

Reading non-UTF-8 encoded files (e.g. .csv or .shp files) with `use_arrow=True` is not supported, but it is typically supported with `use_arrow=False`.
This PR changes the exception thrown so the advice to use `use_arrow=False` is given when appropriate:
``` python
raise DataSourceError("The file being read is not encoded in UTF-8; please use_arrow=False")
```

ENH: raise specific error when trying to read non-UTF-8 file with use_arrow

---

pyogrio/tests/test_core.py
pyogrio/tests/test_geopandas_io.py

It seems that the latest GDAL has improved some error reporting for GPKG (-> https://github.com/OSGeo/gdal/pull/12283), updating our tests to follow those changes

TST: update tests for changed GDAL error for GPKG sql query

---

pyogrio/__init__.py

Avoiding a deprecation warning about accessing `shapely.geos` with shapely >= 2.1

COMPAT: avoid using shapely.geos for recent shapely versions

---

CHANGES.md
pyogrio/_io.pyx
pyogrio/tests/test_geopandas_io.py

Fixes https://github.com/geopandas/geopandas/issues/3625
When a user passes `skip_features` larger than the feature count, we say to return an empty result (changed in https://github.com/geopandas/pyogrio/pull/282). But for some file formats (FileGDB reported in the geopandas issue, and I could also reproduce it for Parquet), our current logic caused GDAL to start reading from the beginning of the file if you also specified explicitly how many features to read with `max_features`

BUG: correctly return empty result for out-of-bounds skip_features for all file formats

---

pyogrio/_err.pyx

The lintian QA tool reported a spelling error for the Debian package build:
* occuring -> occurring

Fix spelling errors.

---

CHANGES.md
pyogrio/_io.pyx
pyogrio/_ogr.pxd
pyogrio/tests/conftest.py
pyogrio/tests/test_arrow.py
pyogrio/tests/test_geopandas_io.py
pyogrio/tests/test_raw_io.py

Add support for all list field types without arrow: list of strings, list of integers and list of double.
closes #17
reference https://github.com/geopandas/geopandas/issues/2113

ENH: add support to read list fields without arrow

---

CHANGES.md
pyogrio/_compat.py
pyogrio/_io.pyx
pyogrio/_ogr.pxd
pyogrio/core.py
pyogrio/geopandas.py
pyogrio/raw.py
pyogrio/tests/conftest.py
pyogrio/tests/test_core.py
pyogrio/tests/test_geopandas_io.py

Changes:
- in `read_dataframe`, if a string fields contain JSON (based on GDAL metadata), they are now parsed and returned as dicts/lists.
- `read_info` now returns two extra pieces of information: the ogr type names and subtype names of all fields/columns.
closes #445

ENH: return JSON fields as dicts in read_dataframe

---

CHANGES.md
pyogrio/_err.pyx
pyogrio/_io.pyx
pyogrio/core.py
pyogrio/tests/test_core.py

This was user error, I was trying to do more or less this
```python
layers = pyogrio.list_layers(...)
infos = [pyogrio.read_info(file, layer) for layer in layers]
```
forgetting that layers doesn't return a list of strings.
Here's a minimal reproducer:
```python
import pyogrio
import geodatasets
pyogrio.read_info(geodatasets.get_path("nybb"), layer=['test']) # segfaults because layer is not a str
```
Still think it's worth this giving a proper error message though.

BUG: fix segfault on giving incorrect type to read_info layer

---

.github/workflows/release.yml
CHANGES.md
ci/manylinux2014_x86_64-vcpkg-gdal.Dockerfile
ci/manylinux_2_28_aarch64-vcpkg-gdal.Dockerfile
ci/manylinux_2_28_x86_64-vcpkg-gdal.Dockerfile
pyproject.toml

Enabling building and testing wheels for Python 3.14 (the tests only run a subset since not all dependencies are available yet for 3.14)

BLD/RLS: build wheels for Python 3.14
